// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrucksSchedule.Infrastructure.Data;

#nullable disable

namespace TruckSchedule.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dea12856-c198-4129-b3f3-b893d8395082",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8f7017ba-1bf3-4787-9d91-132998c6e900",
                            Email = "despatcher01@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "despatcher01@mail.com",
                            NormalizedUserName = "despatcher01@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEPTYngk4MdkXbjRiwNefBDqsU7YB/j3vvphcQgI9Zc9h/W4mIstZ5p3v0oRTOboa2Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "efa089ae-ae1d-4b84-adf0-ec3bdf408da6",
                            TwoFactorEnabled = false,
                            UserName = "despatcher01@mail.com"
                        },
                        new
                        {
                            Id = "6d5800ce-d726-4fc8-83d9-d6b3ac1f591e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aea76059-d922-4f25-ace3-bd225d4ccd23",
                            Email = "juniorDriver@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "juniorDriver@mail.com",
                            NormalizedUserName = "juniorDriver@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEOby0vglEt1QRxVNiN77c8IQYqqMuYcQz7GP/bTMpq9TABqwAxDs8x8GTXaXT+wfig==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5992530d-b818-4c3f-a4e2-8b70cede84b1",
                            TwoFactorEnabled = false,
                            UserName = "juniorDriver@mail.com"
                        },
                        new
                        {
                            Id = "dea12856-c198-4129-83d9-d6b3ac1f591e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d3666b1b-7383-4acf-8275-1c1a35e33e3b",
                            Email = "client001@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "client001@mail.com",
                            NormalizedUserName = "client001@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEGAOTbY715FMddCqq7UfZaWZ05cVUn84yPqPUEFcy0ab9J2nHWPaSzKiRGK95w1m0w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "afa9b36d-16ab-4e38-9125-19aa638edc53",
                            TwoFactorEnabled = false,
                            UserName = "client001@mail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Category Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasComment("Truck category");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Jumbo"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Conestoga"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tautliner"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Tanker"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SemiTrailer"
                        });
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Client Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DespatcherId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Client`s name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Client`s phone number");

                    b.HasKey("Id");

                    b.HasIndex("DespatcherId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.Despatcher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Despatcher identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Despatcher`s name");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasComment("Personal job position number ");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Despatcher`s phone number");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User identifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Despatchers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nikola NIkolov Nikolov",
                            PersonalNumber = "1234567",
                            PhoneNumber = "359894000000",
                            UserId = "dea12856-c198-4129-b3f3-b893d8395082"
                        });
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Driver identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DespatcherId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBusy")
                        .HasColumnType("bit")
                        .HasComment("Point if the driver is available");

                    b.Property<int>("LicenseNumber")
                        .HasMaxLength(8)
                        .HasColumnType("int")
                        .HasComment("Driver`s license number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Driver`s name");

                    b.HasKey("Id");

                    b.HasIndex("DespatcherId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DespatcherId = 1,
                            IsBusy = false,
                            LicenseNumber = 23456789,
                            Name = "Ivan Ivanov Ivanov"
                        },
                        new
                        {
                            Id = 2,
                            DespatcherId = 1,
                            IsBusy = false,
                            LicenseNumber = 67890123,
                            Name = "Stoyan Stoyanov Stoyanov"
                        },
                        new
                        {
                            Id = 3,
                            DespatcherId = 1,
                            IsBusy = false,
                            LicenseNumber = 98765432,
                            Name = "Ivailo Ivailov Ivailov"
                        });
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.DriverTruck", b =>
                {
                    b.Property<int>("TruckId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.HasKey("TruckId", "DriverId");

                    b.HasIndex("DriverId");

                    b.ToTable("DriversTrucks");
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ArrivalPlace")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Trruck`s point of arrival");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2")
                        .HasComment("Estimated date and time of arrival");

                    b.Property<string>("DeparturePlace")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Truck`s point of departure");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of departure");

                    b.Property<int>("Distance")
                        .HasMaxLength(5000)
                        .HasColumnType("int")
                        .HasComment("Route`s total distance");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleated")
                        .HasColumnType("bit")
                        .HasComment("Point if the route is compleated");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Truck Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Company manufactured the truck");

                    b.Property<int>("CargoCapacity")
                        .HasMaxLength(2500)
                        .HasColumnType("int")
                        .HasComment("Cargo capacity");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Cargo type");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("User id of the client, rented the truck");

                    b.Property<int>("DespatcherId")
                        .HasColumnType("int");

                    b.Property<int>("LevelOfLoading")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<bool>("NotAvailable")
                        .HasColumnType("bit")
                        .HasComment("Point out if the Truck is available");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Truck license plate number");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DespatcherId");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.Client", b =>
                {
                    b.HasOne("TruckSchedule.Infrastructure.Data.Models.Despatcher", "Despatcher")
                        .WithMany("Clients")
                        .HasForeignKey("DespatcherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despatcher");
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.Despatcher", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.Driver", b =>
                {
                    b.HasOne("TruckSchedule.Infrastructure.Data.Models.Despatcher", "Despatcher")
                        .WithMany("Drivers")
                        .HasForeignKey("DespatcherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despatcher");
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.DriverTruck", b =>
                {
                    b.HasOne("TruckSchedule.Infrastructure.Data.Models.Driver", "Driver")
                        .WithMany("DriversTrucks")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruckSchedule.Infrastructure.Data.Models.Truck", "Truck")
                        .WithMany("DriversTrucks")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.Route", b =>
                {
                    b.HasOne("TruckSchedule.Infrastructure.Data.Models.Driver", "Driver")
                        .WithMany("Routes")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.Truck", b =>
                {
                    b.HasOne("TruckSchedule.Infrastructure.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruckSchedule.Infrastructure.Data.Models.Despatcher", "Despatcher")
                        .WithMany("Trucks")
                        .HasForeignKey("DespatcherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Despatcher");
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.Despatcher", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Drivers");

                    b.Navigation("Trucks");
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.Driver", b =>
                {
                    b.Navigation("DriversTrucks");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("TruckSchedule.Infrastructure.Data.Models.Truck", b =>
                {
                    b.Navigation("DriversTrucks");
                });
#pragma warning restore 612, 618
        }
    }
}
